# Generated by Django 5.2.1 on 2025-05-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
