# Generated by Django 5.2 on 2025-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_chat_codeentry_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='language_detected',
            field=models.CharField(default='', max_length=100),
        ),
    ]
